source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => "8.0"

link_with 'iOS-mvvm'

pod 'CocoaLumberjack', '1.9.2'

pod 'AFNetworking', '2.5'

pod 'MBProgressHUD', '0.9'

pod 'PureLayout', '2.0.3'

pod 'Mantle', '~> 1.5'

pod 'ReactiveCocoa', '2.3.1'

pod 'ReactiveViewModel', '0.2'

pod 'Overcoat/ReactiveCocoa', '2.1'

pod 'AFNetworkActivityLogger', '2.0.3'

#ignore warnings from pods
inhibit_all_warnings!


# Test
target :'iOS-mvvmTests', :exclusive => true do
	
	pod 'Kiwi', '2.3.1'

end

post_install do |installer|
  installer.project.targets.each do |target|
    puts "#{target.name}"
  end
end
