source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => "8.0"

link_with 'iOS-mvvm'

pod 'CocoaLumberjack', '1.9.2'


#ignore warnings from pods
inhibit_all_warnings!


# Test
target :'iOS-mvvmTests', :exclusive => true do
	
	pod 'Kiwi', '2.3.1'

end

post_install do |installer|
  installer.project.targets.each do |target|
    puts "#{target.name}"
  end
end
